### ISSUE TITLE
Error while running deployment from Azure CLI

### ISSUE THREAD

**Issue by rp2343** [xpillons/azure-hpc#1]
1. Using --template-uri : 
[root@rpatilvm tmp]# az group deployment validate -g HPCTesting --template-uri https://github.com/xpillons/azure-hpc/blob/master/Compute-Grid-Infra/deploy-master.json
{
  "error": {
    "code": "InvalidTemplate",
    "details": null,
    "message": "Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 5, position 1.'.",
    "target": null
  },
  "properties": null
}

2. Using --template-file : 
[root@rpatilvm Compute-Grid-Infra]# az group deployment validate -g HPCTesting --template-file deploy-master.json
{
  "error": {
    "code": "InvalidTemplate",
    "details": null,
    "message": "Deployment template validation failed: 'The template variable 'sharedTemplateUrl' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'.",
    "target": null
  },
  "properties": null
}

**Comment by xpillons** [comment]
The template URI is wrong, please use the RAW URL for it instead of the GitHub one https://raw.githubusercontent.com/xpillons/azure-hpc/master/Compute-Grid-Infra/deploy-master.json
