### ISSUE TITLE
Need to generate valid storage account name

### ISSUE THREAD

**Issue by kanchanm** [xpillons/azure-hpc#2]
The auto generated storage account name didn't meet the storage account name requirements. I got this error while running the compute deployment template. 

Error type
The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is 'e2f07ccf-7c51-4fbd-a22f-e4a0a9f4a913'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details. (Code: InvalidTemplateDeployment)

Error details
Preflight validation failed. Please refer to the details for the specific errors. (Code: PreflightValidationCheckFailed)
-
dm4eji7mvonrikmhpcsersa00 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only. (Code: AccountNameInvalid)

-

falutb3ovxk42kmhpcsersa00 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only. (Code: AccountNameInvalid)
-
zrqfop4wtxzyukmhpcsersa01 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only. (Code: AccountNameInvalid)

-
mt2qpfymbsbeykmhpcsersa01 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only. (Code: AccountNameInvalid)
-
woi2ksa5bmiuqkmhpcsersa02 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only. (Code: AccountNameInvalid)

-

d5qgtp7mzfnk6kmhpcsersa02 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only. (Code: AccountNameInvalid)

**Comment by xpillons** [comment]
Fixed
